# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180123_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creater',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='creater',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='creater',
            new_name='creator',
        ),
    ]
